language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

script:
  - pycodestyle --first compilio.py
  - python setup.py install
  - ls /home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/compilio_cli-0.1.2-py3.6.egg/compilio/
  - compilio
